- 👋 Hi, I’m Sharath Reddy..Friends call me Cherry...
- 👀 I’m interested in learning new things...
- 🌱 I’m currently learning Azure Devops...
- 📫 You can reach me on 9985167788...


<!---
CherryRishi/CherryRishi is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
